# Uncomment the next line to define a global platform for your project
  platform :ios, '9.0'

 #source 'https://cdn.cocoapods.org/'
 #source 'https://github.com/CocoaPods/Specs.git'
 source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'HungryEnglish-Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HungryEnglish-Swift
	#网络请求
	pod 'Alamofire','~> 5.1.0'
	#模型转换
	pod 'HandyJSON'
	pod 'SwiftyJSON'
	#图片处理
	pod 'Kingfisher'
	#约束
  pod 'SnapKit'
end
